# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ecb3e146dc4f7be740028926f595fcbb"
name = "AI Try On By Anrak"
application_url = "https://aitryon-production.up.railway.app"
embedded = true
handle = "ai-try-on-by-anrak"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Mandatory compliance webhooks for Shopify App Store distribution
  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = ["https://aitryon-production.up.railway.app/auth/callback", "https://aitryon-production.up.railway.app/auth/shopify/callback", "https://aitryon-production.up.railway.app/api/auth/callback"]

[pos]
embedded = false
